### ISSUE TITLE
android app crashes after configure hubs

### ISSUE THREAD

**Issue by 410sean** [MarkBryanMilligan/LanternPowerMonitor#25]
after selecting configure hub and granting precise device location permission while using the app, the lantern android app restarts, the next time i select configure hub the app crashes and i see at the bottom app info, close app, or send feedback.

the app continues to crash every time i try configure hub. if i uninstall and reinstall the above repeats.

i am using a samsung s21 ultra 5g

**Comment by MarkBryanMilligan** [comment]
Thanks for the report.  I'll try to get a crash log through the google play console.  If you have an option to report it via the device, please do as that may give me a more detailed crash log.  This must be device specific so I'll figure out what's unique to the s21.

**Comment by MarkBryanMilligan** [comment]
Ok, turns out this is due to a change in Android 12.  I need to request different permissions for Bluetooth than on Android 7.1 - 11.

I just released version 35 of the app to request those new permissions.  It's in google review now but should be available for download in a few hours.  Thanks for finding this, and sorry for the trouble, I should've caught this in the emulator.

**Comment by MarkBryanMilligan** [comment]
It's available in Google Play now, the version displayed is 1.0.20.  Please let me know if it's working now and I'll close this issue.

**Comment by 410sean** [comment]
the new version no longer crashes at the same spot, the permissions bug and crash is resolved. will try to configure the power monitor now.
